# Generated by Django 6.0.5 on 2026-05-26 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0002_comment_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id_client', models.AutoField(db_column='ID_client', primary_key=True, serialize=False)),
                ('client_name', models.CharField(db_collation='Cyrillic_General_CI_AS', db_column='Client_name', max_length=50)),
                ('clientlogin', models.CharField(db_collation='Cyrillic_General_CI_AS', db_column='ClientLogin', max_length=20)),
                ('clientpassword', models.CharField(db_collation='Cyrillic_General_CI_AS', db_column='ClientPassword', max_length=20)),
            ],
            options={
                'db_table': 'clients',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id_employee', models.AutoField(db_column='ID_employee', primary_key=True, serialize=False)),
                ('firstname', models.CharField(db_collation='Cyrillic_General_CI_AS', db_column='FirstName', max_length=50)),
                ('lastname', models.CharField(db_collation='Cyrillic_General_CI_AS', db_column='LastName', max_length=50)),
                ('patronymic', models.CharField(blank=True, db_collation='Cyrillic_General_CI_AS', db_column='Patronymic', max_length=50, null=True)),
                ('employeelogin', models.CharField(db_collation='Cyrillic_General_CI_AS', db_column='EmployeeLogin', max_length=20)),
                ('employeepassword', models.CharField(db_collation='Cyrillic_General_CI_AS', db_column='EmployeePassword', max_length=20)),
            ],
            options={
                'db_table': 'employees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryLogs',
            fields=[
                ('id_log', models.AutoField(db_column='ID_log', primary_key=True, serialize=False)),
                ('logtime', models.DateTimeField(db_column='LogTime')),
                ('change_type', models.CharField(db_collation='Cyrillic_General_CI_AS', db_column='Change_type', max_length=50)),
                ('quantity', models.DecimalField(db_column='Quantity', decimal_places=2, max_digits=10)),
                ('comment', models.CharField(blank=True, db_collation='Cyrillic_General_CI_AS', db_column='Comment', max_length=255, null=True)),
            ],
            options={
                'db_table': 'inventory_logs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id_material', models.AutoField(db_column='ID_material', primary_key=True, serialize=False)),
                ('material_name', models.CharField(db_collation='Cyrillic_General_CI_AS', db_column='Material_name', max_length=100)),
                ('price', models.DecimalField(db_column='Price', decimal_places=2, max_digits=10)),
                ('countonwarehouse', models.DecimalField(db_column='CountOnWarehouse', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'materials',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('pk', models.CompositePrimaryKey('id_order', 'id_product', blank=True, editable=False, primary_key=True, serialize=False)),
                ('product_count', models.IntegerField(db_column='Product_count')),
                ('sale_price', models.DecimalField(db_column='Sale_price', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'order_items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id_order', models.AutoField(db_column='ID_order', primary_key=True, serialize=False)),
                ('ordertime', models.DateTimeField(db_column='OrderTime')),
            ],
            options={
                'db_table': 'orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orderstatuses',
            fields=[
                ('id_orderstatus', models.AutoField(db_column='ID_orderStatus', primary_key=True, serialize=False)),
                ('statusdescription', models.CharField(db_collation='Cyrillic_General_CI_AS', db_column='StatusDescription', max_length=50)),
            ],
            options={
                'db_table': 'orderStatuses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id_producer', models.AutoField(db_column='ID_producer', primary_key=True, serialize=False)),
                ('producer_name', models.CharField(db_collation='Cyrillic_General_CI_AS', db_column='Producer_name', max_length=50)),
                ('prodlogin', models.CharField(db_collation='Cyrillic_General_CI_AS', db_column='ProdLogin', max_length=20)),
                ('prodpassword', models.CharField(db_collation='Cyrillic_General_CI_AS', db_column='ProdPassword', max_length=20)),
            ],
            options={
                'db_table': 'producer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id_product', models.AutoField(db_column='ID_product', primary_key=True, serialize=False)),
                ('product_name', models.CharField(db_collation='Cyrillic_General_CI_AS', db_column='Product_name', max_length=50)),
                ('price', models.DecimalField(db_column='Price', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('pk', models.CompositePrimaryKey('id_product', 'id_material', blank=True, editable=False, primary_key=True, serialize=False)),
                ('material_count', models.DecimalField(db_column='Material_count', decimal_places=3, max_digits=10)),
            ],
            options={
                'db_table': 'recipes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id_role', models.AutoField(db_column='ID_role', primary_key=True, serialize=False)),
                ('roledescription', models.CharField(db_collation='Cyrillic_General_CI_AS', db_column='RoleDescription', max_length=50)),
            ],
            options={
                'db_table': 'roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Shifts',
            fields=[
                ('pk', models.CompositePrimaryKey('id_shift', 'id_worker', blank=True, editable=False, primary_key=True, serialize=False)),
                ('id_shift', models.IntegerField(db_column='ID_shift')),
                ('shift_name', models.CharField(blank=True, db_collation='Cyrillic_General_CI_AS', max_length=100, null=True)),
                ('shifttime', models.DateTimeField(blank=True, db_column='ShiftTime', null=True)),
            ],
            options={
                'db_table': 'shifts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Statuses',
            fields=[
                ('id_status', models.AutoField(db_column='ID_status', primary_key=True, serialize=False)),
                ('statusdescription', models.CharField(db_collation='Cyrillic_General_CI_AS', db_column='StatusDescription', max_length=50)),
            ],
            options={
                'db_table': 'statuses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Supplies',
            fields=[
                ('id_supply', models.AutoField(db_column='ID_supply', primary_key=True, serialize=False)),
                ('supplytime', models.DateTimeField(db_column='SupplyTime')),
            ],
            options={
                'db_table': 'supplies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SupplyItems',
            fields=[
                ('pk', models.CompositePrimaryKey('id_supply', 'id_material', blank=True, editable=False, primary_key=True, serialize=False)),
                ('material_count', models.IntegerField(db_column='Material_count')),
                ('cost_price', models.DecimalField(db_column='Cost_price', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'supply_items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SupplyStatuses',
            fields=[
                ('id_status', models.AutoField(db_column='ID_status', primary_key=True, serialize=False)),
                ('statusname', models.CharField(db_collation='Cyrillic_General_CI_AS', db_column='StatusName', max_length=50)),
            ],
            options={
                'db_table': 'supply_statuses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sysdiagrams',
            fields=[
                ('name', models.CharField(db_collation='Cyrillic_General_CI_AS', max_length=128)),
                ('principal_id', models.IntegerField()),
                ('diagram_id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.IntegerField(blank=True, null=True)),
                ('definition', models.BinaryField(blank=True, max_length='max', null=True)),
            ],
            options={
                'db_table': 'sysdiagrams',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='genres',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='book',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
